apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProductManagement
  labels:
    app: ProductManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProductManagement
  template:
    metadata:
      labels:
        app: ProductManagement
    spec:
      containers:
        - name: ProductManagement
          image: username/ProductManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5